import { Raleway } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";

export const raleway = Raleway({
   subsets: ['latin'],
  variable: '--font-raleway',
  display: 'swap'
})
export const telegraf = localFont({
  src: [
    {
      path: '../../src/fonts/PPTelegraf-Free for personal use/PPTelegraf-Regular.otf',
      style: 'normal'
    },
    {
      path: '../../src/fonts/PPTelegraf-Free for personal use/PPTelegraf-UltraBold.otf',
      style: 'normal'
    },
    {
      path: '../../src/fonts/PPTelegraf-Free for personal use/PPTelegraf-UltraLight.otf',
      style: 'normal'
    }
  ]
})


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${telegraf.variable} ${raleway.variable}`}>{children}</body>
    </html>
  );
}
